I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 10, in script
    $add_inventory(p_inventory, fish, 3)
  File "game/script.rpy", line 10, in <module>
    $add_inventory(p_inventory, fish, 3)
  File "game/functions.rpy", line 5, in add_inventory
    if item.stack == true:
NameError: global name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 10, in script
    $add_inventory(p_inventory, fish, 3)
  File "D:\Gamedev\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Gamedev\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 10, in <module>
    $add_inventory(p_inventory, fish, 3)
  File "game/functions.rpy", line 5, in add_inventory
    if item.stack == true:
NameError: global name 'true' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 7.3.5.606
aTry 1.0
Sat May 30 02:28:35 2020
